// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {database} from '../models';

export function CreateConnection(arg1:models.CreateConnectionInput):Promise<models.Connection>;

export function GetConnections():Promise<Array<models.Connection>>;

export function GetProjectDatabaseStatus():Promise<database.Status>;

export function Greet(arg1:string):Promise<string>;
