// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConnection(arg1) {
  return window['go']['main']['App']['CreateConnection'](arg1);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetProjectDatabaseStatus() {
  return window['go']['main']['App']['GetProjectDatabaseStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
